### ISSUE TITLE
build request: noarch v0.3.1.1

### ISSUE THREAD

**Issue by mfansler** [conda-forge/dill-feedstock#28]
## Issue
The `conda-forge/osx-arm64::apache-beam` builds are unsolvable due to lack of compatible `dill >=0.3.1.1,<0.3.2.0` builds. Further details at conda-forge/apache-beam-feedstock#44.

## Recommendation
Maintainers should attempt issuing a `noarch` build for v0.3.1.1 via a new branch in the repository. This would keep default branch clean while still resolving the issue. This is a one-off request - branch would not need any further maintenance.

See [documentation on using branches to issue alternate versions](https://conda-forge.org/docs/maintainer/updating_pkgs.html#maintaining-several-versions).

**Comment by xylar** [comment]
Should be fixed in #30
