### ISSUE TITLE
Release 0.3.6 claims support for Python < 3.7 but can fail when used

### ISSUE THREAD

**Issue by johnhany97** [conda-forge/dill-feedstock#34]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

dill 0.3.6 only supports Py5hon >= 3.7 - as seen in the release notes here: https://github.com/uqfoundation/dill/releases/tag/dill-0.3.6

But the recipe still claims support for Python >= 3.5.

When used in production, this can yield errors like:
```
...
    import dill
  File "/tmp/conda-a079acb1-abd1-465b-bb1c-fc8df0e4216e/real/environment/lib/python3.6/site-packages/dill/__init__.py", line 26, in <module>
    from ._dill import (
  File "/tmp/conda-a079acb1-abd1-465b-bb1c-fc8df0e4216e/real/environment/lib/python3.6/site-packages/dill/_dill.py", line 117, in <module>
    from types import GetSetDescriptorType, ClassMethodDescriptorType, \
ImportError: cannot import name 'ClassMethodDescriptorType'
```

### Installed packages

```shell
dill
python=3.6
```

### Environment info

```shell
N/A
```

**Comment by xylar** [comment]
@johnhany97, build 0 will still have this problem.  If you try to install dill and python 3.6, you will most likely get build 0. Conda-forge has dropped python 3.6 support awhile ago but obviously it is still available to install.  If this is going to be an issue for you, we could fix build 0 as well.  It's just a bit of a pain.

**Comment by johnhany97** [comment]
For my particular case, we're able to just ensure we never pick build 0 - so no need on my end to do any repodata patching or such.
